AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - bin/**/*
    - db/schema.rb
  DisplayCopNames: true

Rails:
  Enabled: true

Lint/AssignmentInCondition:
  Enabled: false

Lint/EndAlignment:
  AlignWith: variable

Metrics/AbcSize:
  Max: 32

Metrics/ClassLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 4

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 32

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/ClassAndModuleChildren:
  Enabled: false

Style/CommentAnnotation:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/IndentHash:
  EnforcedStyle: consistent

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/NumericLiterals:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: true

Style/MethodCallParentheses:
  Enabled: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
    '%w': '()'
    '%W': '()'

Style/SignalException:
  EnforcedStyle: only_raise
