defaults: &defaults
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
